use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThemeTokens {
    pub bg_primary: String,
    pub bg_secondary: String,
    pub bg_surface: String,
    pub text_primary: String,
    pub text_secondary: String,
    pub text_muted: String,
    pub accent: String,
    pub accent_hover: String,
    pub border: String,
    pub border_active: String,
    pub success: String,
    pub warning: String,
    pub error: String,
    pub info: String,
    pub radius_sm: String,
    pub radius_md: String,
    pub radius_lg: String,
    pub font_family: String,
    pub font_mono: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThemeDefinition {
    pub id: String,
    pub label: String,
    pub tokens: ThemeTokens,
}

pub fn builtin_themes() -> Vec<ThemeDefinition> {
    vec![
        ThemeDefinition {
            id: "midnight".to_string(),
            label: "Midnight".to_string(),
            tokens: ThemeTokens {
                bg_primary: "#0f172a".to_string(),
                bg_secondary: "#1e293b".to_string(),
                bg_surface: "#334155".to_string(),
                text_primary: "#f1f5f9".to_string(),
                text_secondary: "#cbd5e1".to_string(),
                text_muted: "#94a3b8".to_string(),
                accent: "#3b82f6".to_string(),
                accent_hover: "#2563eb".to_string(),
                border: "#475569".to_string(),
                border_active: "#3b82f6".to_string(),
                success: "#22c55e".to_string(),
                warning: "#f59e0b".to_string(),
                error: "#ef4444".to_string(),
                info: "#06b6d4".to_string(),
                radius_sm: "4px".to_string(),
                radius_md: "8px".to_string(),
                radius_lg: "12px".to_string(),
                font_family: "'Inter', ui-sans-serif, system-ui, sans-serif".to_string(),
                font_mono: "'JetBrains Mono', ui-monospace, monospace".to_string(),
            },
        },
        ThemeDefinition {
            id: "obsidian".to_string(),
            label: "Obsidian".to_string(),
            tokens: ThemeTokens {
                bg_primary: "#09090b".to_string(),
                bg_secondary: "#18181b".to_string(),
                bg_surface: "#27272a".to_string(),
                text_primary: "#fafafa".to_string(),
                text_secondary: "#d4d4d8".to_string(),
                text_muted: "#a1a1aa".to_string(),
                accent: "#a78bfa".to_string(),
                accent_hover: "#8b5cf6".to_string(),
                border: "#3f3f46".to_string(),
                border_active: "#a78bfa".to_string(),
                success: "#22c55e".to_string(),
                warning: "#f59e0b".to_string(),
                error: "#ef4444".to_string(),
                info: "#06b6d4".to_string(),
                radius_sm: "4px".to_string(),
                radius_md: "8px".to_string(),
                radius_lg: "12px".to_string(),
                font_family: "'Inter', ui-sans-serif, system-ui, sans-serif".to_string(),
                font_mono: "'JetBrains Mono', ui-monospace, monospace".to_string(),
            },
        },
        ThemeDefinition {
            id: "daylight".to_string(),
            label: "Daylight".to_string(),
            tokens: ThemeTokens {
                bg_primary: "#ffffff".to_string(),
                bg_secondary: "#f8fafc".to_string(),
                bg_surface: "#f1f5f9".to_string(),
                text_primary: "#0f172a".to_string(),
                text_secondary: "#475569".to_string(),
                text_muted: "#94a3b8".to_string(),
                accent: "#2563eb".to_string(),
                accent_hover: "#1d4ed8".to_string(),
                border: "#e2e8f0".to_string(),
                border_active: "#2563eb".to_string(),
                success: "#16a34a".to_string(),
                warning: "#d97706".to_string(),
                error: "#dc2626".to_string(),
                info: "#0891b2".to_string(),
                radius_sm: "4px".to_string(),
                radius_md: "8px".to_string(),
                radius_lg: "12px".to_string(),
                font_family: "'Inter', ui-sans-serif, system-ui, sans-serif".to_string(),
                font_mono: "'JetBrains Mono', ui-monospace, monospace".to_string(),
            },
        },
        ThemeDefinition {
            id: "carvana-blue".to_string(),
            label: "Carvana Blue".to_string(),
            tokens: ThemeTokens {
                bg_primary: "#0c1929".to_string(),
                bg_secondary: "#142338".to_string(),
                bg_surface: "#1e3350".to_string(),
                text_primary: "#e0f2fe".to_string(),
                text_secondary: "#93c5fd".to_string(),
                text_muted: "#60a5fa".to_string(),
                accent: "#00b4d8".to_string(),
                accent_hover: "#0891b2".to_string(),
                border: "#1e3a5f".to_string(),
                border_active: "#00b4d8".to_string(),
                success: "#22c55e".to_string(),
                warning: "#f59e0b".to_string(),
                error: "#ef4444".to_string(),
                info: "#38bdf8".to_string(),
                radius_sm: "4px".to_string(),
                radius_md: "8px".to_string(),
                radius_lg: "12px".to_string(),
                font_family: "'Inter', ui-sans-serif, system-ui, sans-serif".to_string(),
                font_mono: "'JetBrains Mono', ui-monospace, monospace".to_string(),
            },
        },
    ]
}
